// Configuração de magias extraídas do Canary original
export const SPELLS = {
  KNIGHT: [
    {
      id: 'exura_infir_ico',
      name: 'Bruise Bane',
      words: 'exura infir ico',
      mana: 10,
      level: 1,
      type: 'heal',
      icon: '💚',
      description: 'Bruise Bane (exura infir ico) - 10 MP, Lv. 1',
      heal: 21
    },
    {
      id: 'exori_infir_min',
      name: 'Lesser Front Sweep',
      words: 'exori infir min',
      mana: 6,
      level: 1,
      type: 'attack',
      icon: '⚔️',
      description: 'Lesser Front Sweep (exori infir min) - 6 MP, Lv. 1',
      damage: 14
    },
    {
      id: 'exura_ico',
      name: 'Wound Cleansing',
      words: 'exura ico',
      mana: 40,
      level: 8,
      type: 'heal',
      icon: '💚',
      description: 'Wound Cleansing (exura ico) - 40 MP, Lv. 8',
      heal: 88
    },
    {
      id: 'exana_pox',
      name: 'Cure Poison',
      words: 'exana pox',
      mana: 30,
      level: 10,
      type: 'heal',
      icon: '💚',
      description: 'Cure Poison (exana pox) - 30 MP, Lv. 10',
      heal: 70
    },
    {
      id: 'exori_ico',
      name: 'Brutal Strike',
      words: 'exori ico',
      mana: 30,
      level: 16,
      type: 'attack',
      icon: '⚔️',
      description: 'Brutal Strike (exori ico) - 30 MP, Lv. 16',
      damage: 92
    },
    {
      id: 'exori_hur',
      name: 'Whirlwind Throw',
      words: 'exori hur',
      mana: 40,
      level: 28,
      type: 'attack',
      icon: '⚔️',
      description: 'Whirlwind Throw (exori hur) - 40 MP, Lv. 28',
      damage: 136
    },
    {
      id: 'exori_mas',
      name: 'Groundshaker',
      words: 'exori mas',
      mana: 160,
      level: 33,
      type: 'aoe',
      icon: '🌊',
      description: 'Groundshaker (exori mas) - 160 MP, Lv. 33',
      damage: 386
    },
    {
      id: 'exori',
      name: 'Berserk',
      words: 'exori',
      mana: 115,
      level: 35,
      type: 'attack',
      icon: '⚔️',
      description: 'Berserk (exori) - 115 MP, Lv. 35',
      damage: 300
    },
    {
      id: 'utori_kor',
      name: 'Inflict Wound',
      words: 'utori kor',
      mana: 30,
      level: 40,
      type: 'attack',
      icon: '⚔️',
      description: 'Inflict Wound (utori kor) - 30 MP, Lv. 40',
      damage: 140
    },
    {
      id: 'exana_kor',
      name: 'Cure Bleeding',
      words: 'exana kor',
      mana: 30,
      level: 45,
      type: 'heal',
      icon: '💚',
      description: 'Cure Bleeding (exana kor) - 30 MP, Lv. 45',
      heal: 105
    },
    {
      id: 'utura',
      name: 'Recovery',
      words: 'utura',
      mana: 75,
      level: 50,
      type: 'heal',
      icon: '💚',
      description: 'Recovery (utura) - 75 MP, Lv. 50',
      heal: 200
    },
    {
      id: 'exori_min',
      name: 'Front Sweep',
      words: 'exori min',
      mana: 200,
      level: 70,
      type: 'attack',
      icon: '⚔️',
      description: 'Front Sweep (exori min) - 200 MP, Lv. 70',
      damage: 540
    },
    {
      id: 'exura_gran_ico',
      name: 'Intense Wound Cleansing',
      words: 'exura gran ico',
      mana: 200,
      level: 80,
      type: 'heal',
      icon: '💚',
      description: 'Intense Wound Cleansing (exura gran ico) - 200 MP, Lv. 80',
      heal: 480
    },
    {
      id: 'exori_gran',
      name: 'Fierce Berserk',
      words: 'exori gran',
      mana: 340,
      level: 90,
      type: 'attack',
      icon: '⚔️',
      description: 'Fierce Berserk (exori gran) - 340 MP, Lv. 90',
      damage: 860
    },
    {
      id: 'utura_gran',
      name: 'Intense Recovery',
      words: 'utura gran',
      mana: 165,
      level: 100,
      type: 'heal',
      icon: '💚',
      description: 'Intense Recovery (utura gran) - 165 MP, Lv. 100',
      heal: 430
    },
    {
      id: 'exori_gran_ico',
      name: 'Annihilation',
      words: 'exori gran ico',
      mana: 300,
      level: 110,
      type: 'attack',
      icon: '⚔️',
      description: 'Annihilation (exori gran ico) - 300 MP, Lv. 110',
      damage: 820
    },
    {
      id: 'exori_amp_kor',
      name: 'Executioner's Throw',
      words: 'exori amp kor',
      mana: 225,
      level: 300,
      type: 'attack',
      icon: '⚔️',
      description: 'Executioner's Throw (exori amp kor) - 225 MP, Lv. 300',
      damage: 1050
    },
    {
      id: 'exura_med_ico',
      name: 'Fair Wound Cleansing',
      words: 'exura med ico',
      mana: 90,
      level: 300,
      type: 'heal',
      icon: '💚',
      description: 'Fair Wound Cleansing (exura med ico) - 90 MP, Lv. 300',
      heal: 480
    }
  ],
  PALADIN: [
    {
      id: 'exori_infir_con',
      name: 'Lesser Ethereal Spear',
      words: 'exori infir con',
      mana: 6,
      level: 1,
      type: 'attack',
      icon: '⚔️',
      description: 'Lesser Ethereal Spear (exori infir con) - 6 MP, Lv. 1',
      damage: 14
    },
    {
      id: 'exura_infir',
      name: 'Magic Patch',
      words: 'exura infir',
      mana: 6,
      level: 1,
      type: 'heal',
      icon: '💚',
      description: 'Magic Patch (exura infir) - 6 MP, Lv. 1',
      heal: 13
    },
    {
      id: 'exura',
      name: 'Light Healing',
      words: 'exura',
      mana: 20,
      level: 8,
      type: 'heal',
      icon: '💚',
      description: 'Light Healing (exura) - 20 MP, Lv. 8',
      heal: 48
    },
    {
      id: 'exana_pox',
      name: 'Cure Poison',
      words: 'exana pox',
      mana: 30,
      level: 10,
      type: 'heal',
      icon: '💚',
      description: 'Cure Poison (exana pox) - 30 MP, Lv. 10',
      heal: 70
    },
    {
      id: 'exura_gran',
      name: 'Intense Healing',
      words: 'exura gran',
      mana: 70,
      level: 20,
      type: 'heal',
      icon: '💚',
      description: 'Intense Healing (exura gran) - 70 MP, Lv. 20',
      heal: 160
    },
    {
      id: 'exori_con',
      name: 'Ethereal Spear',
      words: 'exori con',
      mana: 25,
      level: 23,
      type: 'attack',
      icon: '⚔️',
      description: 'Ethereal Spear (exori con) - 25 MP, Lv. 23',
      damage: 96
    },
    {
      id: 'exura_san',
      name: 'Divine Healing',
      words: 'exura san',
      mana: 160,
      level: 35,
      type: 'heal',
      icon: '💚',
      description: 'Divine Healing (exura san) - 160 MP, Lv. 35',
      heal: 355
    },
    {
      id: 'exori_san',
      name: 'Divine Missile',
      words: 'exori san',
      mana: 20,
      level: 40,
      type: 'attack',
      icon: '🏹',
      description: 'Divine Missile (exori san) - 20 MP, Lv. 40',
      damage: 120
    },
    {
      id: 'exevo_mas_san',
      name: 'Divine Caldera',
      words: 'exevo mas san',
      mana: 160,
      level: 50,
      type: 'aoe',
      icon: '🏹',
      description: 'Divine Caldera (exevo mas san) - 160 MP, Lv. 50',
      damage: 420
    },
    {
      id: 'utura',
      name: 'Recovery',
      words: 'utura',
      mana: 75,
      level: 50,
      type: 'heal',
      icon: '💚',
      description: 'Recovery (utura) - 75 MP, Lv. 50',
      heal: 200
    },
    {
      id: 'exura_gran_san',
      name: 'Salvation',
      words: 'exura gran san',
      mana: 210,
      level: 60,
      type: 'heal',
      icon: '💚',
      description: 'Salvation (exura gran san) - 210 MP, Lv. 60',
      heal: 480
    },
    {
      id: 'utori_san',
      name: 'Holy Flash',
      words: 'utori san',
      mana: 30,
      level: 70,
      type: 'attack',
      icon: '🏹',
      description: 'Holy Flash (utori san) - 30 MP, Lv. 70',
      damage: 200
    },
    {
      id: 'exana_mort',
      name: 'Cure Curse',
      words: 'exana mort',
      mana: 40,
      level: 80,
      type: 'heal',
      icon: '💚',
      description: 'Cure Curse (exana mort) - 40 MP, Lv. 80',
      heal: 160
    },
    {
      id: 'exori_gran_con',
      name: 'Strong Ethereal Spear',
      words: 'exori gran con',
      mana: 55,
      level: 90,
      type: 'attack',
      icon: '⚔️',
      description: 'Strong Ethereal Spear (exori gran con) - 55 MP, Lv. 90',
      damage: 290
    },
    {
      id: 'utura_gran',
      name: 'Intense Recovery',
      words: 'utura gran',
      mana: 165,
      level: 100,
      type: 'heal',
      icon: '💚',
      description: 'Intense Recovery (utura gran) - 165 MP, Lv. 100',
      heal: 430
    },
    {
      id: 'exevo_tempo_mas_san',
      name: 'Divine Grenade',
      words: 'exevo tempo mas san',
      mana: 160,
      level: 300,
      type: 'aoe',
      icon: '🏹',
      description: 'Divine Grenade (exevo tempo mas san) - 160 MP, Lv. 300',
      damage: 920
    }
  ],
  SORCERER: [
    {
      id: 'exori_infir_vis',
      name: 'Buzz',
      words: 'exori infir vis',
      mana: 6,
      level: 1,
      type: 'attack',
      icon: '⚡',
      description: 'Buzz (exori infir vis) - 6 MP, Lv. 1',
      damage: 14
    },
    {
      id: 'exura_infir',
      name: 'Magic Patch',
      words: 'exura infir',
      mana: 6,
      level: 1,
      type: 'heal',
      icon: '💚',
      description: 'Magic Patch (exura infir) - 6 MP, Lv. 1',
      heal: 13
    },
    {
      id: 'exevo_infir_flam_hur',
      name: 'Scorch',
      words: 'exevo infir flam hur',
      mana: 8,
      level: 1,
      type: 'aoe',
      icon: '🔥',
      description: 'Scorch (exevo infir flam hur) - 8 MP, Lv. 1',
      damage: 18
    },
    {
      id: 'exori_min_flam',
      name: 'Apprentice's Strike',
      words: 'exori min flam',
      mana: 6,
      level: 8,
      type: 'attack',
      icon: '🔥',
      description: 'Apprentice's Strike (exori min flam) - 6 MP, Lv. 8',
      damage: 28
    },
    {
      id: 'exura',
      name: 'Light Healing',
      words: 'exura',
      mana: 20,
      level: 8,
      type: 'heal',
      icon: '💚',
      description: 'Light Healing (exura) - 20 MP, Lv. 8',
      heal: 48
    },
    {
      id: 'exana_pox',
      name: 'Cure Poison',
      words: 'exana pox',
      mana: 30,
      level: 10,
      type: 'heal',
      icon: '💚',
      description: 'Cure Poison (exana pox) - 30 MP, Lv. 10',
      heal: 70
    },
    {
      id: 'exori_vis',
      name: 'Energy Strike',
      words: 'exori vis',
      mana: 20,
      level: 12,
      type: 'attack',
      icon: '⚡',
      description: 'Energy Strike (exori vis) - 20 MP, Lv. 12',
      damage: 64
    },
    {
      id: 'exori_tera',
      name: 'Terra Strike',
      words: 'exori tera',
      mana: 20,
      level: 13,
      type: 'attack',
      icon: '🌍',
      description: 'Terra Strike (exori tera) - 20 MP, Lv. 13',
      damage: 66
    },
    {
      id: 'exori_flam',
      name: 'Flame Strike',
      words: 'exori flam',
      mana: 20,
      level: 14,
      type: 'attack',
      icon: '🔥',
      description: 'Flame Strike (exori flam) - 20 MP, Lv. 14',
      damage: 68
    },
    {
      id: 'exori_frigo',
      name: 'Ice Strike',
      words: 'exori frigo',
      mana: 20,
      level: 15,
      type: 'attack',
      icon: '❄️',
      description: 'Ice Strike (exori frigo) - 20 MP, Lv. 15',
      damage: 70
    },
    {
      id: 'exori_mort',
      name: 'Death Strike',
      words: 'exori mort',
      mana: 20,
      level: 16,
      type: 'attack',
      icon: '⚔️',
      description: 'Death Strike (exori mort) - 20 MP, Lv. 16',
      damage: 72
    },
    {
      id: 'exevo_flam_hur',
      name: 'Fire Wave',
      words: 'exevo flam hur',
      mana: 25,
      level: 18,
      type: 'aoe',
      icon: '🔥',
      description: 'Fire Wave (exevo flam hur) - 25 MP, Lv. 18',
      damage: 86
    },
    {
      id: 'exura_gran',
      name: 'Intense Healing',
      words: 'exura gran',
      mana: 70,
      level: 20,
      type: 'heal',
      icon: '💚',
      description: 'Intense Healing (exura gran) - 70 MP, Lv. 20',
      heal: 160
    },
    {
      id: 'exevo_vis_lux',
      name: 'Energy Beam',
      words: 'exevo vis lux',
      mana: 40,
      level: 23,
      type: 'aoe',
      icon: '⚡',
      description: 'Energy Beam (exevo vis lux) - 40 MP, Lv. 23',
      damage: 126
    },
    {
      id: 'utori_flam',
      name: 'Ignite',
      words: 'utori flam',
      mana: 30,
      level: 26,
      type: 'attack',
      icon: '🔥',
      description: 'Ignite (utori flam) - 30 MP, Lv. 26',
      damage: 112
    },
    {
      id: 'exevo_gran_vis_lux',
      name: 'Great Energy Beam',
      words: 'exevo gran vis lux',
      mana: 110,
      level: 29,
      type: 'aoe',
      icon: '⚡',
      description: 'Great Energy Beam (exevo gran vis lux) - 110 MP, Lv. 29',
      damage: 278
    },
    {
      id: 'exura_vita',
      name: 'Ultimate Healing',
      words: 'exura vita',
      mana: 160,
      level: 30,
      type: 'heal',
      icon: '💚',
      description: 'Ultimate Healing (exura vita) - 160 MP, Lv. 30',
      heal: 350
    },
    {
      id: 'utori_vis',
      name: 'Electrify',
      words: 'utori vis',
      mana: 30,
      level: 34,
      type: 'attack',
      icon: '⚡',
      description: 'Electrify (utori vis) - 30 MP, Lv. 34',
      damage: 128
    },
    {
      id: 'exevo_vis_hur',
      name: 'Energy Wave',
      words: 'exevo vis hur',
      mana: 170,
      level: 38,
      type: 'aoe',
      icon: '⚡',
      description: 'Energy Wave (exevo vis hur) - 170 MP, Lv. 38',
      damage: 416
    },
    {
      id: 'exevo_gran_flam_hur',
      name: 'Great Fire Wave',
      words: 'exevo gran flam hur',
      mana: 120,
      level: 38,
      type: 'aoe',
      icon: '🔥',
      description: 'Great Fire Wave (exevo gran flam hur) - 120 MP, Lv. 38',
      damage: 316
    },
    {
      id: 'exori_amp_vis',
      name: 'Lightning',
      words: 'exori amp vis',
      mana: 60,
      level: 55,
      type: 'attack',
      icon: '⚡',
      description: 'Lightning (exori amp vis) - 60 MP, Lv. 55',
      damage: 230
    },
    {
      id: 'exevo_gran_mas_vis',
      name: 'Rage of the Skies',
      words: 'exevo gran mas vis',
      mana: 600,
      level: 55,
      type: 'aoe',
      icon: '⚡',
      description: 'Rage of the Skies (exevo gran mas vis) - 600 MP, Lv. 55',
      damage: 1310
    },
    {
      id: 'exevo_gran_mas_flam',
      name: 'Hell's Core',
      words: 'exevo gran mas flam',
      mana: 1100,
      level: 60,
      type: 'aoe',
      icon: '🔥',
      description: 'Hell's Core (exevo gran mas flam) - 1100 MP, Lv. 60',
      damage: 2320
    },
    {
      id: 'exori_gran_flam',
      name: 'Strong Flame Strike',
      words: 'exori gran flam',
      mana: 60,
      level: 70,
      type: 'attack',
      icon: '🔥',
      description: 'Strong Flame Strike (exori gran flam) - 60 MP, Lv. 70',
      damage: 260
    },
    {
      id: 'utori_mort',
      name: 'Curse',
      words: 'utori mort',
      mana: 30,
      level: 75,
      type: 'attack',
      icon: '⚔️',
      description: 'Curse (utori mort) - 30 MP, Lv. 75',
      damage: 210
    },
    {
      id: 'exori_gran_vis',
      name: 'Strong Energy Strike',
      words: 'exori gran vis',
      mana: 60,
      level: 80,
      type: 'attack',
      icon: '⚡',
      description: 'Strong Energy Strike (exori gran vis) - 60 MP, Lv. 80',
      damage: 280
    },
    {
      id: 'exori_max_flam',
      name: 'Ultimate Flame Strike',
      words: 'exori max flam',
      mana: 100,
      level: 90,
      type: 'attack',
      icon: '🔥',
      description: 'Ultimate Flame Strike (exori max flam) - 100 MP, Lv. 90',
      damage: 380
    },
    {
      id: 'exori_max_vis',
      name: 'Ultimate Energy Strike',
      words: 'exori max vis',
      mana: 100,
      level: 100,
      type: 'attack',
      icon: '⚡',
      description: 'Ultimate Energy Strike (exori max vis) - 100 MP, Lv. 100',
      damage: 400
    },
    {
      id: 'exevo_max_mort',
      name: 'Great Death Beam',
      words: 'exevo max mort',
      mana: 140,
      level: 300,
      type: 'aoe',
      icon: '🌊',
      description: 'Great Death Beam (exevo max mort) - 140 MP, Lv. 300',
      damage: 880
    },
    {
      id: 'exura_max_vita',
      name: 'Restoration',
      words: 'exura max vita',
      mana: 260,
      level: 300,
      type: 'heal',
      icon: '💚',
      description: 'Restoration (exura max vita) - 260 MP, Lv. 300',
      heal: 820
    }
  ],
  DRUID: [
    {
      id: 'exevo_infir_frigo_hur',
      name: 'Chill Out',
      words: 'exevo infir frigo hur',
      mana: 8,
      level: 1,
      type: 'aoe',
      icon: '❄️',
      description: 'Chill Out (exevo infir frigo hur) - 8 MP, Lv. 1',
      damage: 18
    },
    {
      id: 'exura_infir',
      name: 'Magic Patch',
      words: 'exura infir',
      mana: 6,
      level: 1,
      type: 'heal',
      icon: '💚',
      description: 'Magic Patch (exura infir) - 6 MP, Lv. 1',
      heal: 13
    },
    {
      id: 'exori_infir_tera',
      name: 'Mud Attack',
      words: 'exori infir tera',
      mana: 6,
      level: 1,
      type: 'attack',
      icon: '🌍',
      description: 'Mud Attack (exori infir tera) - 6 MP, Lv. 1',
      damage: 14
    },
    {
      id: 'exori_min_flam',
      name: 'Apprentice's Strike',
      words: 'exori min flam',
      mana: 6,
      level: 8,
      type: 'attack',
      icon: '🔥',
      description: 'Apprentice's Strike (exori min flam) - 6 MP, Lv. 8',
      damage: 28
    },
    {
      id: 'exura',
      name: 'Light Healing',
      words: 'exura',
      mana: 20,
      level: 8,
      type: 'heal',
      icon: '💚',
      description: 'Light Healing (exura) - 20 MP, Lv. 8',
      heal: 48
    },
    {
      id: 'exana_pox',
      name: 'Cure Poison',
      words: 'exana pox',
      mana: 30,
      level: 10,
      type: 'heal',
      icon: '💚',
      description: 'Cure Poison (exana pox) - 30 MP, Lv. 10',
      heal: 70
    },
    {
      id: 'exori_vis',
      name: 'Energy Strike',
      words: 'exori vis',
      mana: 20,
      level: 12,
      type: 'attack',
      icon: '⚡',
      description: 'Energy Strike (exori vis) - 20 MP, Lv. 12',
      damage: 64
    },
    {
      id: 'exori_tera',
      name: 'Terra Strike',
      words: 'exori tera',
      mana: 20,
      level: 13,
      type: 'attack',
      icon: '🌍',
      description: 'Terra Strike (exori tera) - 20 MP, Lv. 13',
      damage: 66
    },
    {
      id: 'exori_flam',
      name: 'Flame Strike',
      words: 'exori flam',
      mana: 20,
      level: 14,
      type: 'attack',
      icon: '🔥',
      description: 'Flame Strike (exori flam) - 20 MP, Lv. 14',
      damage: 68
    },
    {
      id: 'exori_frigo',
      name: 'Ice Strike',
      words: 'exori frigo',
      mana: 20,
      level: 15,
      type: 'attack',
      icon: '❄️',
      description: 'Ice Strike (exori frigo) - 20 MP, Lv. 15',
      damage: 70
    },
    {
      id: 'exori_moe_ico',
      name: 'Physical Strike',
      words: 'exori moe ico',
      mana: 20,
      level: 16,
      type: 'attack',
      icon: '⚔️',
      description: 'Physical Strike (exori moe ico) - 20 MP, Lv. 16',
      damage: 72
    },
    {
      id: 'exura_sio',
      name: 'Heal Friend',
      words: 'exura sio',
      mana: 120,
      level: 18,
      type: 'heal',
      icon: '💚',
      description: 'Heal Friend (exura sio) - 120 MP, Lv. 18',
      heal: 258
    },
    {
      id: 'exevo_frigo_hur',
      name: 'Ice Wave',
      words: 'exevo frigo hur',
      mana: 25,
      level: 18,
      type: 'aoe',
      icon: '❄️',
      description: 'Ice Wave (exevo frigo hur) - 25 MP, Lv. 18',
      damage: 86
    },
    {
      id: 'exura_gran',
      name: 'Intense Healing',
      words: 'exura gran',
      mana: 70,
      level: 20,
      type: 'heal',
      icon: '💚',
      description: 'Intense Healing (exura gran) - 70 MP, Lv. 20',
      heal: 160
    },
    {
      id: 'exana_vis',
      name: 'Cure Electrification',
      words: 'exana vis',
      mana: 30,
      level: 22,
      type: 'heal',
      icon: '💚',
      description: 'Cure Electrification (exana vis) - 30 MP, Lv. 22',
      heal: 82
    },
    {
      id: 'exana_flam',
      name: 'Cure Burning',
      words: 'exana flam',
      mana: 30,
      level: 30,
      type: 'heal',
      icon: '💚',
      description: 'Cure Burning (exana flam) - 30 MP, Lv. 30',
      heal: 90
    },
    {
      id: 'exura_vita',
      name: 'Ultimate Healing',
      words: 'exura vita',
      mana: 160,
      level: 30,
      type: 'heal',
      icon: '💚',
      description: 'Ultimate Healing (exura vita) - 160 MP, Lv. 30',
      heal: 350
    },
    {
      id: 'exura_gran_mas_res',
      name: 'Mass Healing',
      words: 'exura gran mas res',
      mana: 150,
      level: 36,
      type: 'heal',
      icon: '💚',
      description: 'Mass Healing (exura gran mas res) - 150 MP, Lv. 36',
      heal: 336
    },
    {
      id: 'exevo_tera_hur',
      name: 'Terra Wave',
      words: 'exevo tera hur',
      mana: 170,
      level: 38,
      type: 'aoe',
      icon: '🌍',
      description: 'Terra Wave (exevo tera hur) - 170 MP, Lv. 38',
      damage: 416
    },
    {
      id: 'exevo_gran_frigo_hur',
      name: 'Strong Ice Wave',
      words: 'exevo gran frigo hur',
      mana: 170,
      level: 40,
      type: 'aoe',
      icon: '❄️',
      description: 'Strong Ice Wave (exevo gran frigo hur) - 170 MP, Lv. 40',
      damage: 420
    },
    {
      id: 'exana_kor',
      name: 'Cure Bleeding',
      words: 'exana kor',
      mana: 30,
      level: 45,
      type: 'heal',
      icon: '💚',
      description: 'Cure Bleeding (exana kor) - 30 MP, Lv. 45',
      heal: 105
    },
    {
      id: 'utori_pox',
      name: 'Envenom',
      words: 'utori pox',
      mana: 30,
      level: 50,
      type: 'attack',
      icon: '⚔️',
      description: 'Envenom (utori pox) - 30 MP, Lv. 50',
      damage: 160
    },
    {
      id: 'exevo_gran_mas_tera',
      name: 'Wrath of Nature',
      words: 'exevo gran mas tera',
      mana: 700,
      level: 55,
      type: 'aoe',
      icon: '🌍',
      description: 'Wrath of Nature (exevo gran mas tera) - 700 MP, Lv. 55',
      damage: 1510
    },
    {
      id: 'exevo_gran_mas_frigo',
      name: 'Eternal Winter',
      words: 'exevo gran mas frigo',
      mana: 1050,
      level: 60,
      type: 'aoe',
      icon: '❄️',
      description: 'Eternal Winter (exevo gran mas frigo) - 1050 MP, Lv. 60',
      damage: 2220
    },
    {
      id: 'exori_gran_tera',
      name: 'Strong Terra Strike',
      words: 'exori gran tera',
      mana: 60,
      level: 70,
      type: 'attack',
      icon: '🌍',
      description: 'Strong Terra Strike (exori gran tera) - 60 MP, Lv. 70',
      damage: 260
    },
    {
      id: 'exori_gran_frigo',
      name: 'Strong Ice Strike',
      words: 'exori gran frigo',
      mana: 60,
      level: 80,
      type: 'attack',
      icon: '❄️',
      description: 'Strong Ice Strike (exori gran frigo) - 60 MP, Lv. 80',
      damage: 280
    },
    {
      id: 'exori_max_tera',
      name: 'Ultimate Terra Strike',
      words: 'exori max tera',
      mana: 100,
      level: 90,
      type: 'attack',
      icon: '🌍',
      description: 'Ultimate Terra Strike (exori max tera) - 100 MP, Lv. 90',
      damage: 380
    },
    {
      id: 'exori_max_frigo',
      name: 'Ultimate Ice Strike',
      words: 'exori max frigo',
      mana: 100,
      level: 100,
      type: 'attack',
      icon: '❄️',
      description: 'Ultimate Ice Strike (exori max frigo) - 100 MP, Lv. 100',
      damage: 400
    },
    {
      id: 'exevo_ulus_frigo',
      name: 'Ice Burst',
      words: 'exevo ulus frigo',
      mana: 230,
      level: 300,
      type: 'aoe',
      icon: '❄️',
      description: 'Ice Burst (exevo ulus frigo) - 230 MP, Lv. 300',
      damage: 1060
    },
    {
      id: 'exura_gran_sio',
      name: 'Nature's Embrace',
      words: 'exura gran sio',
      mana: 400,
      level: 300,
      type: 'heal',
      icon: '💚',
      description: 'Nature's Embrace (exura gran sio) - 400 MP, Lv. 300',
      heal: 1100
    },
    {
      id: 'exura_max_vita',
      name: 'Restoration',
      words: 'exura max vita',
      mana: 260,
      level: 300,
      type: 'heal',
      icon: '💚',
      description: 'Restoration (exura max vita) - 260 MP, Lv. 300',
      heal: 820
    },
    {
      id: 'exevo_ulus_tera',
      name: 'Terra Burst',
      words: 'exevo ulus tera',
      mana: 230,
      level: 300,
      type: 'aoe',
      icon: '🌍',
      description: 'Terra Burst (exevo ulus tera) - 230 MP, Lv. 300',
      damage: 1060
    }
  ],
  MONK: [
    {
      id: 'exori_gran_mas_nia',
      name: 'Spiritual Outburst',
      words: 'exori gran mas nia',
      mana: 425,
      level: 0,
      type: 'aoe',
      icon: '🌊',
      description: 'Spiritual Outburst (exori gran mas nia) - 425 MP, Lv. 0',
      damage: 850
    },
    {
      id: 'exori_infir_pug',
      name: 'Swift Jab',
      words: 'exori infir pug',
      mana: 3,
      level: 0,
      type: 'attack',
      icon: '⚔️',
      description: 'Swift Jab (exori infir pug) - 3 MP, Lv. 0',
      damage: 6
    },
    {
      id: 'exori_infir_nia',
      name: 'Tiger Clash',
      words: 'exori infir nia',
      mana: 3,
      level: 0,
      type: 'attack',
      icon: '⚔️',
      description: 'Tiger Clash (exori infir nia) - 3 MP, Lv. 0',
      damage: 6
    },
    {
      id: 'exura_infir',
      name: 'Magic Patch',
      words: 'exura infir',
      mana: 6,
      level: 1,
      type: 'heal',
      icon: '💚',
      description: 'Magic Patch (exura infir) - 6 MP, Lv. 1',
      heal: 13
    },
    {
      id: 'exura',
      name: 'Light Healing',
      words: 'exura',
      mana: 20,
      level: 8,
      type: 'heal',
      icon: '💚',
      description: 'Light Healing (exura) - 20 MP, Lv. 8',
      heal: 48
    },
    {
      id: 'exana_pox',
      name: 'Cure Poison',
      words: 'exana pox',
      mana: 30,
      level: 10,
      type: 'heal',
      icon: '💚',
      description: 'Cure Poison (exana pox) - 30 MP, Lv. 10',
      heal: 70
    },
    {
      id: 'exori_pug',
      name: 'Double Jab',
      words: 'exori pug',
      mana: 30,
      level: 14,
      type: 'attack',
      icon: '⚔️',
      description: 'Double Jab (exori pug) - 30 MP, Lv. 14',
      damage: 88
    },
    {
      id: 'exori_nia',
      name: 'Greater Tiger Clash',
      words: 'exori nia',
      mana: 50,
      level: 18,
      type: 'attack',
      icon: '⚔️',
      description: 'Greater Tiger Clash (exori nia) - 50 MP, Lv. 18',
      damage: 136
    },
    {
      id: 'exura_tio_sio',
      name: 'Restore Balance',
      words: 'exura tio sio',
      mana: 120,
      level: 18,
      type: 'heal',
      icon: '💚',
      description: 'Restore Balance (exura tio sio) - 120 MP, Lv. 18',
      heal: 258
    },
    {
      id: 'exura_gran',
      name: 'Intense Healing',
      words: 'exura gran',
      mana: 70,
      level: 20,
      type: 'heal',
      icon: '💚',
      description: 'Intense Healing (exura gran) - 70 MP, Lv. 20',
      heal: 160
    },
    {
      id: 'exori_amp_pug',
      name: 'Mystic Repulse',
      words: 'exori amp pug',
      mana: 150,
      level: 30,
      type: 'attack',
      icon: '⚔️',
      description: 'Mystic Repulse (exori amp pug) - 150 MP, Lv. 30',
      damage: 360
    },
    {
      id: 'exori_mas_pug',
      name: 'Flurry of Blows',
      words: 'exori mas pug',
      mana: 110,
      level: 35,
      type: 'aoe',
      icon: '🌊',
      description: 'Flurry of Blows (exori mas pug) - 110 MP, Lv. 35',
      damage: 290
    },
    {
      id: 'utori_kor',
      name: 'Inflict Wound',
      words: 'utori kor',
      mana: 30,
      level: 40,
      type: 'attack',
      icon: '⚔️',
      description: 'Inflict Wound (utori kor) - 30 MP, Lv. 40',
      damage: 140
    },
    {
      id: 'exori_mas_nia',
      name: 'Sweeping Takedown',
      words: 'exori mas nia',
      mana: 210,
      level: 60,
      type: 'aoe',
      icon: '🌊',
      description: 'Sweeping Takedown (exori mas nia) - 210 MP, Lv. 60',
      damage: 540
    },
    {
      id: 'exori_med_pug',
      name: 'Chained Penance',
      words: 'exori med pug',
      mana: 180,
      level: 70,
      type: 'attack',
      icon: '⚔️',
      description: 'Chained Penance (exori med pug) - 180 MP, Lv. 70',
      damage: 500
    },
    {
      id: 'exura_gran_tio',
      name: 'Spirit Mend',
      words: 'exura gran tio',
      mana: 210,
      level: 80,
      type: 'heal',
      icon: '💚',
      description: 'Spirit Mend (exura gran tio) - 210 MP, Lv. 80',
      heal: 500
    },
    {
      id: 'exori_gran_mas_pug',
      name: 'Greater Flurry of Blows',
      words: 'exori gran mas pug',
      mana: 300,
      level: 90,
      type: 'aoe',
      icon: '🌊',
      description: 'Greater Flurry of Blows (exori gran mas pug) - 300 MP, Lv. 90',
      damage: 780
    },
    {
      id: 'exori_gran_pug',
      name: 'Forceful Uppercut',
      words: 'exori gran pug',
      mana: 325,
      level: 110,
      type: 'attack',
      icon: '⚔️',
      description: 'Forceful Uppercut (exori gran pug) - 325 MP, Lv. 110',
      damage: 870
    },
    {
      id: 'exori_gran_nia',
      name: 'Devastating Knockout',
      words: 'exori gran nia',
      mana: 210,
      level: 125,
      type: 'attack',
      icon: '⚔️',
      description: 'Devastating Knockout (exori gran nia) - 210 MP, Lv. 125',
      damage: 670
    },
    {
      id: 'exura_mas_nia',
      name: 'Mass Spirit Mend',
      words: 'exura mas nia',
      mana: 250,
      level: 150,
      type: 'heal',
      icon: '💚',
      description: 'Mass Spirit Mend (exura mas nia) - 250 MP, Lv. 150',
      heal: 650
    }
  ]
};
export default SPELLS;
